# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/Project/200t/AM_demodulation/AM_demodulation.srcs/sources_1/ip/fir_lowpass_25k/fir_lowpass_25k.xci
# IP: The module: 'fir_lowpass_25k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/AM_demodulation/AM_demodulation.gen/sources_1/ip/fir_lowpass_25k/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_lowpass_25k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/Project/200t/AM_demodulation/AM_demodulation.gen/sources_1/ip/fir_lowpass_25k/fir_lowpass_25k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_lowpass_25k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Xilinx/Project/200t/AM_demodulation/AM_demodulation.srcs/sources_1/ip/fir_lowpass_25k/fir_lowpass_25k.xci
# IP: The module: 'fir_lowpass_25k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/AM_demodulation/AM_demodulation.gen/sources_1/ip/fir_lowpass_25k/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_lowpass_25k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/Project/200t/AM_demodulation/AM_demodulation.gen/sources_1/ip/fir_lowpass_25k/fir_lowpass_25k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_lowpass_25k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
